from tkinter import *
window=Tk()
btn=Button(window, text="Submit", fg='blue')
btn.place(x=80, y=100)
lbl=Label(window, text="CS Helper", fg='red', font=("Helvetica", 16))
lbl.place(x=60, y=50)
txtfld=Entry(window, text="How May I Help You?", bd=5)
txtfld.place(x=80, y=150)
window.title('CS Helper')
window.geometry("300x200+10+10")
window.mainloop()