info = [
    (
        "C S",
        "111",
        "M01",
        "MA",
        "4",
        "CS PRINCIPLES",
        "TR",
        "0900-1015",
        "SH",
        "115",
        "Shaun H. Cooper (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "111L",
        "M01",
        "MA",
        "0",
        "CS PRINCIPLES-LAB",
        "W",
        "1030-1220",
        "SH",
        "118B",
        "Shaun H. Cooper",
        "01/22-05/15",
    ),
    (
        "C S",
        "111",
        "M03",
        "MA",
        "4",
        "CS PRINCIPLES",
        "MTWR",
        "1220-1340",
        "TBA",
        "-",
        "Thomas Ehret (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "151",
        "M70",
        "MA",
        "3",
        "C++ PROGRAMMING",
        "TBA",
        "-",
        "MAONWB",
        "WEB",
        "Yuming Zhang (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "153",
        "M70",
        "MA",
        "3",
        "PYTHON PROGRAMMING I",
        "TBA",
        "-",
        "MAONWB",
        "WEB",
        "Esther Davis Steiner (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "158",
        "M70",
        "MA",
        "3",
        "R PROGRAMMING I",
        "TBA",
        "-",
        "MAONWB",
        "WEB",
        "Ruby Sharma (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "171G",
        "M70",
        "MA",
        "4",
        "INTRO TO COMPUTER SCI",
        "TBA",
        "-",
        "MAONWB",
        "WEB",
        "Khandker Mushfiqul Islam (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "172",
        "M01",
        "MA",
        "4",
        "COMPUTER SCIENCE I",
        "TR",
        "0900-1015",
        "GT",
        "337",
        "Inna V. Pivkina (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "172L",
        "M01",
        "MA",
        "0",
        "COMPUTER SCIENCE I-LAB",
        "M",
        "1030-1220",
        "SH",
        "118",
        "Inna V. Pivkina",
        "01/22-05/15",
    ),
    (
        "C S",
        "172",
        "M02",
        "MA",
        "4",
        "COMPUTER SCIENCE I",
        "TR",
        "0900-1015",
        "GT",
        "337",
        "Inna V. Pivkina (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "172L",
        "M02",
        "MA",
        "0",
        "COMPUTER SCIENCE I-LAB",
        "W",
        "1030-1220",
        "SH",
        "118",
        "Inna V. Pivkina",
        "01/22-05/15",
    ),
    (
        "C S",
        "271",
        "M01",
        "MA",
        "4",
        "O O PROGRAMMING",
        "TR",
        "0900-1015",
        "SH",
        "107",
        "Esther Davis Steiner (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "271L",
        "M01",
        "MA",
        "0",
        "O O PROGRAMMING-LAB",
        "T",
        "1630-1820",
        "SH",
        "118B",
        "Esther Davis Steiner",
        "01/22-05/15",
    ),
    (
        "C S",
        "271",
        "M02",
        "MA",
        "4",
        "O O PROGRAMMING",
        "TR",
        "0900-1015",
        "SH",
        "107",
        "Esther Davis Steiner (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "271L",
        "M02",
        "MA",
        "0",
        "O O PROGRAMMING-LAB",
        "R",
        "1630-1820",
        "SH",
        "118B",
        "Esther Davis Steiner",
        "01/22-05/15",
    ),
    (
        "C S",
        "272",
        "M01",
        "MA",
        "4",
        "INTRDN-DATA STRCTRS",
        "MW",
        "1330-1445",
        "SH",
        "107",
        "Huiping Cao (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "272L",
        "M01",
        "MA",
        "0",
        "INTRDN-DATA STRCTRS-LAB",
        "M",
        "1630-1820",
        "SH",
        "118",
        "Huiping Cao",
        "01/22-05/15",
    ),
    (
        "C S",
        "272",
        "M02",
        "MA",
        "4",
        "INTRDN-DATA STRCTRS",
        "MW",
        "1330-1445",
        "SH",
        "107",
        "Huiping Cao (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "272L",
        "M02",
        "MA",
        "0",
        "INTRDN-DATA STRCTRS-LAB",
        "W",
        "1630-1820",
        "SH",
        "118",
        "Huiping Cao",
        "01/22-05/15",
    ),
    (
        "C S",
        "273",
        "M01",
        "MA",
        "4",
        "MACHINE PROG & ORG",
        "TR",
        "1030-1145",
        "SH",
        "115",
        "Shaun H. Cooper (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "273L",
        "M01",
        "MA",
        "0",
        "MACHINE PROG & ORG-LAB",
        "T",
        "1630-1820",
        "SH",
        "118",
        "Shaun H. Cooper",
        "01/22-05/15",
    ),
    (
        "C S",
        "273",
        "M02",
        "MA",
        "4",
        "MACHINE PROG & ORG",
        "TR",
        "1030-1145",
        "SH",
        "115",
        "Shaun H. Cooper (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "273L",
        "M02",
        "MA",
        "0",
        "MACHINE PROG & ORG-LAB",
        "R",
        "1630-1820",
        "SH",
        "118",
        "Shaun H. Cooper",
        "01/22-05/15",
    ),
    (
        "C S",
        "278",
        "M01",
        "MA",
        "4",
        "DISCRETE MATH FOR CS",
        "TR",
        "0730-0845",
        "SH",
        "107",
        "Esther Davis Steiner (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "278L",
        "M01",
        "MA",
        "0",
        "DISCRETE MATH FOR CS-LAB",
        "M",
        "1630-1820",
        "SH",
        "107",
        "Esther Davis Steiner",
        "01/22-05/15",
    ),
    (
        "C S",
        "278",
        "M02",
        "MA",
        "4",
        "DISCRETE MATH FOR CS",
        "TR",
        "0730-0845",
        "SH",
        "107",
        "Esther Davis Steiner (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "278L",
        "M02",
        "MA",
        "0",
        "DISCRETE MATH FOR CS-LAB",
        "W",
        "1630-1820",
        "SH",
        "107",
        "Esther Davis Steiner",
        "01/22-05/15",
    ),
    (
        "C S",
        "370",
        "M01",
        "MA",
        "4",
        "COMPILERS & AUTOMATA",
        "MW",
        "0900-1015",
        "SH",
        "115",
        "Shaun H. Cooper (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "370L",
        "M01",
        "MA",
        "0",
        "COMPILERS & AUTOMATA-LAB",
        "F",
        "1030-1220",
        "SH",
        "118B",
        "Shaun H. Cooper",
        "01/22-05/15",
    ),
    (
        "C S",
        "371",
        "M01",
        "MA",
        "4",
        "SOFTWARE DEVELOPMENT",
        "MW",
        "1030-1145",
        "SH",
        "115",
        "Jonathan E. Cook (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "371L",
        "M01",
        "MA",
        "0",
        "SOFTWARE DEVELOPMENT-LAB",
        "F",
        "1300-1450",
        "SH",
        "118",
        "Jonathan E. Cook",
        "01/22-05/15",
    ),
    (
        "C S",
        "371",
        "M02",
        "MA",
        "4",
        "SOFTWARE DEVELOPMENT",
        "TBA",
        "-",
        "MANCR",
        "NCR",
        "Enrico Pontelli (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "372",
        "M01",
        "MA",
        "4",
        "DATA STRCTRS & ALGRTHMS",
        "TR",
        "1200-1315",
        "SH",
        "106",
        "Inna V. Pivkina (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "372L",
        "M01",
        "MA",
        "0",
        "DATA STRCTRS & ALGRTHMS-LAB",
        "W",
        "1300-1450",
        "SH",
        "106",
        "Inna V. Pivkina",
        "01/22-05/15",
    ),
    (
        "C S",
        "372",
        "M02",
        "MA",
        "4",
        "DATA STRCTRS & ALGRTHMS",
        "TBA",
        "-",
        "MANCR",
        "NCR",
        "Enrico Pontelli (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "409",
        "M01",
        "MA",
        "1-6",
        "INDEPENDENT STUDY",
        "TBA",
        "-",
        "MANCR",
        "NCR",
        "Zachary Oliver Toups (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "409",
        "M02",
        "MA",
        "1-6",
        "INDEPENDENT STUDY",
        "TBA",
        "-",
        "MANCR",
        "NCR",
        "Zachary Oliver Toups (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "409",
        "M03",
        "MA",
        "1-6",
        "INDEPENDENT STUDY",
        "TBA",
        "-",
        "MANCR",
        "NCR",
        "Son Cao Tran (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "409",
        "M04",
        "MA",
        "1-6",
        "INDEPENDENT STUDY",
        "TBA",
        "-",
        "MANCR",
        "NCR",
        "Roopa Vishwanathan (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "409",
        "M05",
        "MA",
        "1-6",
        "INDEPENDENT STUDY",
        "TBA",
        "-",
        "MANCR",
        "NCR",
        "Roopa Vishwanathan (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "409",
        "M06",
        "MA",
        "1-6",
        "INDEPENDENT STUDY",
        "TBA",
        "-",
        "MANCR",
        "NCR",
        "Enrico Pontelli (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "409",
        "M07",
        "MA",
        "1-6",
        "INDEPENDENT STUDY",
        "TBA",
        "-",
        "MANCR",
        "NCR",
        "William A Hamilton (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "409",
        "M08",
        "MA",
        "1-6",
        "INDEPENDENT STUDY",
        "WF",
        "1600-1700",
        "MANCR",
        "NCR",
        "Adan Delval (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "409",
        "M09",
        "MA",
        "1-6",
        "INDEPENDENT STUDY",
        "TBA",
        "-",
        "MANCR",
        "NCR",
        "Enrico Pontelli (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "419",
        "M01",
        "MA",
        "1",
        "ETHICS AND COMPUTING",
        "M",
        "1630-1720",
        "SH",
        "107",
        "Shaun H. Cooper (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "448",
        "M01",
        "MA",
        "4",
        "SENIOR PROJECT",
        "MW",
        "1500-1615",
        "SH",
        "118B",
        "Ivan Strnad (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "448L",
        "M01",
        "MA",
        "0",
        "SENIOR PROJECT-LAB",
        "F",
        "1300-1550",
        "SH",
        "118B",
        "TBA",
        "01/22-05/15",
    ),
    (
        "C S",
        "449",
        "M01",
        "MA",
        "4",
        "SENIOR THESIS",
        "TBA",
        "-",
        "MANCR",
        "NCR",
        "Huiping Cao (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "449",
        "M02",
        "MA",
        "4",
        "SENIOR THESIS",
        "TBA",
        "-",
        "MANCR",
        "NCR",
        "Zachary Oliver Toups (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "449",
        "M03",
        "MA",
        "4",
        "SENIOR THESIS",
        "TBA",
        "-",
        "MANCR",
        "NCR",
        "Satyajayant Misra (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "449",
        "M04",
        "MA",
        "4",
        "SENIOR THESIS",
        "TBA",
        "-",
        "MANCR",
        "NCR",
        "Satyajayant Misra (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "449",
        "M05",
        "MA",
        "4",
        "SENIOR THESIS",
        "TBA",
        "-",
        "MANCR",
        "NCR",
        "Son Cao Tran (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "449",
        "M06",
        "MA",
        "4",
        "SENIOR THESIS",
        "TBA",
        "-",
        "MANCR",
        "NCR",
        "Parth P Nagarkar (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "449",
        "M07",
        "MA",
        "4",
        "SENIOR THESIS",
        "TBA",
        "-",
        "MANCR",
        "NCR",
        "Inna V. Pivkina (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "449",
        "M08",
        "MA",
        "4",
        "SENIOR THESIS",
        "TBA",
        "-",
        "MANCR",
        "NCR",
        "Jonathan E. Cook (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "449",
        "M09",
        "MA",
        "4",
        "SENIOR THESIS",
        "TBA",
        "-",
        "MANCR",
        "NCR",
        "William A Hamilton (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "449",
        "M10",
        "MA",
        "4",
        "SENIOR THESIS",
        "TBA",
        "-",
        "MANCR",
        "NCR",
        "Enrico Pontelli (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "451",
        "M70",
        "MA",
        "3",
        "C++ PROGRAMMING",
        "TBA",
        "-",
        "MAONWB",
        "WEB",
        "Yuming Zhang (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "453",
        "M70",
        "MA",
        "3",
        "PYTHON PROGRAMMING I",
        "TBA",
        "-",
        "MAONWB",
        "WEB",
        "Esther Davis Steiner (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "458",
        "M70",
        "MA",
        "3",
        "R PROGRAMMING I",
        "TBA",
        "-",
        "MAONWB",
        "WEB",
        "Ruby Sharma (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "460",
        "M01",
        "MA",
        "3",
        "CS I TRANSITION",
        "TR",
        "0900-1015",
        "GT",
        "337",
        "Inna V. Pivkina (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "462",
        "M01",
        "MA",
        "3",
        "O O PROGRAMMING TRANSITION",
        "TR",
        "0900-1015",
        "SH",
        "107",
        "Esther Davis Steiner (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "463",
        "M01",
        "MA",
        "3",
        "DATA STRUCTURES TRANSITION",
        "MW",
        "1330-1445",
        "SH",
        "107",
        "Huiping Cao (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "464",
        "M01",
        "MA",
        "3",
        "MACHINE ORG.TRANSITION",
        "TR",
        "1030-1145",
        "SH",
        "115",
        "Shaun H. Cooper (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "465",
        "M01",
        "MA",
        "3",
        "DISCRETE MATH TRANSITION",
        "TR",
        "0730-0845",
        "SH",
        "107",
        "Esther Davis Steiner (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "466",
        "M01",
        "MA",
        "3",
        "COMPILERS TRANSITION",
        "MW",
        "0900-1015",
        "SH",
        "115",
        "Shaun H. Cooper (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "468",
        "M01",
        "MA",
        "3",
        "SW DEVELOPMENT TRANSITION",
        "MW",
        "1030-1145",
        "SH",
        "115",
        "Jonathan E. Cook (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "469",
        "M01",
        "MA",
        "3",
        "ALGORITHMS TRANSITION",
        "TR",
        "1200-1315",
        "SH",
        "106",
        "Inna V. Pivkina (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "473",
        "M01",
        "MA",
        "3",
        "ARCHITECTURAL CNCPT 1",
        "MW",
        "1200-1315",
        "JH",
        "109",
        "A. K. Petersen (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "475",
        "M01",
        "MA",
        "3",
        "ARTIFICIAL INTLGNCE I",
        "MW",
        "1030-1145",
        "SH",
        "113",
        "Son Cao Tran (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "478",
        "M01",
        "MA",
        "3",
        "COMPUTER SECURITY",
        "TR",
        "1200-1315",
        "SH",
        "110",
        "Roopa Vishwanathan (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "479",
        "M01",
        "MA",
        "3",
        "SPECIAL TOPICS",
        "TR",
        "1500-1615",
        "SH",
        "113",
        "Roopa Vishwanathan (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "479",
        "M02",
        "MA",
        "3",
        "Special Topics: Blockchain",
        "TR",
        "1200-1315",
        "SH",
        "115",
        "Satyajayant Misra (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "479",
        "M03",
        "MA",
        "3",
        "Special Topics: Big Data",
        "MW",
        "1200-1315",
        "SH",
        "113",
        "Tuan Le (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "479",
        "M04",
        "MA",
        "3",
        "Special Topics: Virtual Reality",
        "TR",
        "0900-1015",
        "SH",
        "118B",
        "Zachary Oliver Toups (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "479",
        "M05",
        "MA",
        "3",
        "Special Topics: Web and Internet Programming",
        "MW",
        "1330-1445",
        "SH",
        "283",
        "William A Hamilton (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "479",
        "M06",
        "MA",
        "3",
        "Special Topics: Emerging Topics in Security",
        "TR",
        "1330-1445",
        "SH",
        "113",
        "Tao Wang (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "479",
        "M07",
        "MA",
        "3",
        "Special Topics: Entrepreneurship and Lean Startups",
        "TBA",
        "-",
        "MANCR",
        "NCR",
        "Enrico Pontelli (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "479",
        "M08",
        "MA",
        "3",
        "Special Topics: Product Management",
        "TBA",
        "-",
        "MANCR",
        "NCR",
        "Enrico Pontelli (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "479",
        "M09",
        "MA",
        "3",
        "Special Topics: Quantum Computing",
        "MW",
        "1330-1445",
        "JH",
        "215",
        "Boris Kiefer",
        "01/22-05/15",
    ),
    (
        "C S",
        "479L",
        "M09",
        "MA",
        "0",
        "Special Topics: Quantum Computing-LAB",
        "MW",
        "1330-1445",
        "JH",
        "215",
        "John Harding",
        "01/22-05/15",
    ),
    (
        "C S",
        "479LL",
        "M09",
        "MA",
        "0",
        "Special Topics: Quantum Computing-LAB-LAB",
        "MW",
        "1330-1445",
        "JH",
        "215",
        "Phillip L. DeLeon",
        "01/22-05/15",
    ),
    (
        "C S",
        "479LLL",
        "M09",
        "MA",
        "0",
        "Special Topics: Quantum Computing-LAB-LAB-LAB",
        "MW",
        "1330-1445",
        "JH",
        "215",
        "Satyajayant Misra (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "479LLLL",
        "M09",
        "MA",
        "0",
        "Special Topics: Quantum Computing-LAB-LAB-LAB-LAB",
        "MW",
        "1330-1445",
        "JH",
        "215",
        "David G Mitchell",
        "01/22-05/15",
    ),
    (
        "C S",
        "479LLLLL",
        "M09",
        "MA",
        "0",
        "Special Topics: Quantum Computing-LAB-LAB-LAB-LAB-LAB",
        "MW",
        "1330-1445",
        "JH",
        "215",
        "Abdel-Hameed S Badawy",
        "01/22-05/15",
    ),
    (
        "C S",
        "482",
        "M01",
        "MA",
        "3",
        "DATABASE MGT SYS I",
        "TBA",
        "-",
        "MANCR",
        "NCR",
        "Enrico Pontelli (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "482",
        "M70",
        "MA",
        "3",
        "DATABASE MGT SYS I",
        "TBA",
        "-",
        "MAONWB",
        "WEB",
        "Parth P Nagarkar (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "485",
        "M01",
        "MA",
        "3",
        "HUMAN-CENTERED COMPUTING",
        "TBA",
        "-",
        "MANCR",
        "NCR",
        "Enrico Pontelli (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "486",
        "M01",
        "MA",
        "3",
        "BIOINFORMATICS",
        "TR",
        "1630-1745",
        "SH",
        "113",
        "Mingzhou Song (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "487",
        "M01",
        "MA",
        "3",
        "APPLIED ML I",
        "MW",
        "0900-1015",
        "SH",
        "118B",
        "Huiping Cao (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "487",
        "M02",
        "MA",
        "3",
        "APPLIED ML I",
        "TBA",
        "-",
        "MANCR",
        "NCR",
        "Enrico Pontelli (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "487",
        "M70",
        "MA",
        "3",
        "APPLIED ML I",
        "TBA",
        "-",
        "MAONWB",
        "WEB",
        "Huiping Cao (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "502",
        "M70",
        "MA",
        "3",
        "DATABASE MGT SYS I",
        "TBA",
        "-",
        "MAONWB",
        "WEB",
        "Parth P Nagarkar (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "505",
        "M01",
        "MA",
        "3",
        "ARTIFICIAL INTEL I",
        "MW",
        "1030-1145",
        "SH",
        "113",
        "Son Cao Tran (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "513",
        "M01",
        "MA",
        "3",
        "COMPUTER SECURITY",
        "TR",
        "1200-1315",
        "SH",
        "110",
        "Roopa Vishwanathan (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "516",
        "M01",
        "MA",
        "3",
        "BIOINFORMATICS",
        "TR",
        "1630-1745",
        "SH",
        "113",
        "Mingzhou Song (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "519",
        "M01",
        "MA",
        "3",
        "APPLIED ML I",
        "MW",
        "0900-1015",
        "SH",
        "118B",
        "Huiping Cao (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "519",
        "M70",
        "MA",
        "3",
        "APPLIED ML I",
        "TBA",
        "-",
        "MANCR",
        "NCR",
        "Huiping Cao (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "570",
        "M01",
        "MA",
        "3",
        "ANALYSIS OF ALGORITHMS",
        "TR",
        "1330-1445",
        "SH",
        "115",
        "Mingzhou Song (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "579",
        "M01",
        "MA",
        "3",
        "Advanced Cryptography",
        "TR",
        "1500-1615",
        "SH",
        "113",
        "Roopa Vishwanathan (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "579",
        "M02",
        "MA",
        "3",
        "Special Topics: Blockchain",
        "TR",
        "1200-1315",
        "SH",
        "115",
        "Satyajayant Misra (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "579",
        "M03",
        "MA",
        "3",
        "Special Topics: Big Data",
        "MW",
        "1200-1315",
        "SH",
        "113",
        "Tuan Le (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "579",
        "M04",
        "MA",
        "3",
        "Special Topics: Virtual Reality",
        "TR",
        "0900-1015",
        "SH",
        "118B",
        "Zachary Oliver Toups (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "579",
        "M05",
        "MA",
        "3",
        "Special Topics: Web and Internet Programming",
        "MW",
        "1330-1445",
        "SH",
        "283",
        "William A Hamilton (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "579",
        "M06",
        "MA",
        "3",
        "Special Topics: Emerging Topics in Security",
        "TR",
        "1330-1445",
        "SH",
        "113",
        "Tao Wang (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "579",
        "M07",
        "MA",
        "3",
        "Special Topics: Quantum Computing",
        "MW",
        "1330-1445",
        "JH",
        "215",
        "Boris Kiefer",
        "01/22-05/15",
    ),
    (
        "C S",
        "579L",
        "M07",
        "MA",
        "0",
        "Special Topics: Quantum Computing-LAB",
        "MW",
        "1330-1445",
        "JH",
        "215",
        "John Harding",
        "01/22-05/15",
    ),
    (
        "C S",
        "579LL",
        "M07",
        "MA",
        "0",
        "Special Topics: Quantum Computing-LAB-LAB",
        "MW",
        "1330-1445",
        "JH",
        "215",
        "Abdel-Hameed S Badawy",
        "01/22-05/15",
    ),
    (
        "C S",
        "579LLL",
        "M07",
        "MA",
        "0",
        "Special Topics: Quantum Computing-LAB-LAB-LAB",
        "MW",
        "1330-1445",
        "JH",
        "215",
        "David G Mitchell",
        "01/22-05/15",
    ),
    (
        "C S",
        "579LLLL",
        "M07",
        "MA",
        "0",
        "Special Topics: Quantum Computing-LAB-LAB-LAB-LAB",
        "MW",
        "1330-1445",
        "JH",
        "215",
        "Satyajayant Misra (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "579LLLLL",
        "M07",
        "MA",
        "0",
        "Special Topics: Quantum Computing-LAB-LAB-LAB-LAB-LAB",
        "MW",
        "1330-1445",
        "JH",
        "215",
        "Phillip L. DeLeon",
        "01/22-05/15",
    ),
    (
        "C S",
        "581",
        "M01",
        "MA",
        "3",
        "ADV SOFTWARE ENGR",
        "TR",
        "1200-1315",
        "SH",
        "118B",
        "Jonathan E. Cook (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "582",
        "M01",
        "MA",
        "3",
        "DATABASE MGT SYST II",
        "TR",
        "1500-1615",
        "SH",
        "115",
        "Parth P Nagarkar (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "584",
        "M01",
        "MA",
        "3",
        "COMPUTER NETWORKS II",
        "TR",
        "1500-1615",
        "SH",
        "118B",
        "Satyajayant Misra (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "589",
        "M01",
        "MA",
        "1-6",
        "SPCL RES PROBLEMS",
        "TBA",
        "-",
        "MANCR",
        "NCR",
        "Huiping Cao (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "589",
        "M02",
        "MA",
        "1-6",
        "SPCL RES PROBLEMS",
        "TBA",
        "-",
        "MANCR",
        "NCR",
        "Jonathan E. Cook (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "589",
        "M03",
        "MA",
        "3",
        "SPCL RES PROBLEMS",
        "TBA",
        "-",
        "MANCR",
        "NCR",
        "Shaun H. Cooper (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "589",
        "M04",
        "MA",
        "1-6",
        "Special Research Problems: Independent Research Study",
        "TBA",
        "-",
        "MANCR",
        "NCR",
        "Tuan Le (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "589",
        "M05",
        "MA",
        "1-6",
        "SPCL RES PROBLEMS",
        "TBA",
        "-",
        "MANCR",
        "NCR",
        "Satyajayant Misra (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "589",
        "M06",
        "MA",
        "1-6",
        "SPCL RES PROBLEMS",
        "TBA",
        "-",
        "MANCR",
        "NCR",
        "Inna V. Pivkina (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "589",
        "M07",
        "MA",
        "1-6",
        "SPCL RES PROBLEMS",
        "TBA",
        "-",
        "MANCR",
        "NCR",
        "Enrico Pontelli (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "589",
        "M08",
        "MA",
        "1-6",
        "SPCL RES PROBLEMS",
        "TBA",
        "-",
        "MANCR",
        "NCR",
        "Mingzhou Song (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "589",
        "M09",
        "MA",
        "1-6",
        "SPCL RES PROBLEMS",
        "TBA",
        "-",
        "MANCR",
        "NCR",
        "Son Cao Tran (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "589",
        "M10",
        "MA",
        "1-6",
        "SPCL RES PROBLEMS",
        "TBA",
        "-",
        "MANCR",
        "NCR",
        "Parth P Nagarkar (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "589",
        "M11",
        "MA",
        "1-6",
        "SPCL RES PROBLEMS",
        "TBA",
        "-",
        "MANCR",
        "NCR",
        "Roopa Vishwanathan (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "589",
        "M12",
        "MA",
        "1-6",
        "SPCL RES PROBLEMS",
        "TBA",
        "-",
        "MANCR",
        "NCR",
        "Zachary Oliver Toups (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "589",
        "M13",
        "MA",
        "1-6",
        "SPCL RES PROBLEMS",
        "TBA",
        "-",
        "MANCR",
        "NCR",
        "William A Hamilton (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "589",
        "M14",
        "MA",
        "3",
        "SPCL RES PROBLEMS",
        "TBA",
        "-",
        "MANCR",
        "NCR",
        "Satyajayant Misra (P)",
        "03/30-05/15",
    ),
    (
        "C S",
        "598",
        "M01",
        "MA",
        "1-6",
        "MASTER'S PROJECT",
        "TBA",
        "-",
        "MANCR",
        "NCR",
        "Huiping Cao (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "598",
        "M02",
        "MA",
        "1-6",
        "MASTER'S PROJECT",
        "TBA",
        "-",
        "MANCR",
        "NCR",
        "Jonathan E. Cook (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "598",
        "M03",
        "MA",
        "1-6",
        "MASTER'S PROJECT",
        "TBA",
        "-",
        "MANCR",
        "NCR",
        "Parth P Nagarkar (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "598",
        "M05",
        "MA",
        "1-6",
        "MASTER'S PROJECT",
        "TBA",
        "-",
        "MANCR",
        "NCR",
        "Satyajayant Misra (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "598",
        "M06",
        "MA",
        "1-6",
        "MASTER'S PROJECT",
        "TBA",
        "-",
        "MANCR",
        "NCR",
        "Inna V. Pivkina (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "598",
        "M07",
        "MA",
        "1-6",
        "MASTER'S PROJECT",
        "TBA",
        "-",
        "MANCR",
        "NCR",
        "Enrico Pontelli (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "598",
        "M08",
        "MA",
        "1-6",
        "MASTER'S PROJECT",
        "TBA",
        "-",
        "MANCR",
        "NCR",
        "Mingzhou Song (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "598",
        "M09",
        "MA",
        "1-6",
        "MASTER'S PROJECT",
        "TBA",
        "-",
        "MANCR",
        "NCR",
        "Son Cao Tran (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "598",
        "M12",
        "MA",
        "1-6",
        "MASTER'S PROJECT",
        "TBA",
        "-",
        "MANCR",
        "NCR",
        "Zachary Oliver Toups (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "598",
        "M30",
        "MA",
        "1-6",
        "MASTER'S PROJECT",
        "TBA",
        "-",
        "MANCR",
        "NCR",
        "Parth P Nagarkar (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "599",
        "M01",
        "MA",
        "1-6",
        "MASTER'S THESIS",
        "TBA",
        "-",
        "MANCR",
        "NCR",
        "Huiping Cao (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "599",
        "M02",
        "MA",
        "1-6",
        "MASTER'S THESIS",
        "TBA",
        "-",
        "MANCR",
        "NCR",
        "Jonathan E. Cook (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "599",
        "M03",
        "MA",
        "1-6",
        "MASTER'S THESIS",
        "TBA",
        "-",
        "MANCR",
        "NCR",
        "Parth P Nagarkar (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "599",
        "M05",
        "MA",
        "1-6",
        "MASTER'S THESIS",
        "TBA",
        "-",
        "MANCR",
        "NCR",
        "Satyajayant Misra (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "599",
        "M06",
        "MA",
        "1-6",
        "MASTER'S THESIS",
        "TBA",
        "-",
        "MANCR",
        "NCR",
        "Inna V. Pivkina (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "599",
        "M07",
        "MA",
        "1-6",
        "MASTER'S THESIS",
        "TBA",
        "-",
        "MANCR",
        "NCR",
        "Enrico Pontelli (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "599",
        "M08",
        "MA",
        "1-6",
        "MASTER'S THESIS",
        "TBA",
        "-",
        "MANCR",
        "NCR",
        "Mingzhou Song (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "599",
        "M09",
        "MA",
        "1-6",
        "MASTER'S THESIS",
        "TBA",
        "-",
        "MANCR",
        "NCR",
        "Son Cao Tran (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "599",
        "M10",
        "MA",
        "1-6",
        "MASTER'S THESIS",
        "TBA",
        "-",
        "MANCR",
        "NCR",
        "Roopa Vishwanathan (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "599",
        "M12",
        "MA",
        "1-6",
        "MASTER'S THESIS",
        "TBA",
        "-",
        "MANCR",
        "NCR",
        "Zachary Oliver Toups (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "600",
        "M01",
        "MA",
        "1-15",
        "PREDISSERTATION RSCH",
        "TBA",
        "-",
        "MANCR",
        "NCR",
        "Huiping Cao (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "600",
        "M02",
        "MA",
        "1-15",
        "PREDISSERTATION RSCH",
        "TBA",
        "-",
        "MANCR",
        "NCR",
        "Jonathan E. Cook (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "600",
        "M03",
        "MA",
        "1-15",
        "PREDISSERTATION RSCH",
        "TBA",
        "-",
        "MANCR",
        "NCR",
        "William A Hamilton (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "600",
        "M04",
        "MA",
        "1-15",
        "PREDISSERTATION RSCH",
        "TBA",
        "-",
        "MANCR",
        "NCR",
        "Parth P Nagarkar (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "600",
        "M05",
        "MA",
        "1-15",
        "PREDISSERTATION RSCH",
        "TBA",
        "-",
        "MANCR",
        "NCR",
        "Satyajayant Misra (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "600",
        "M06",
        "MA",
        "1-15",
        "PREDISSERTATION RSCH",
        "TBA",
        "-",
        "MANCR",
        "NCR",
        "Inna V. Pivkina (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "600",
        "M07",
        "MA",
        "1-15",
        "PREDISSERTATION RSCH",
        "TBA",
        "-",
        "MANCR",
        "NCR",
        "Enrico Pontelli (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "600",
        "M08",
        "MA",
        "1-15",
        "PREDISSERTATION RSCH",
        "TBA",
        "-",
        "MANCR",
        "NCR",
        "Mingzhou Song (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "600",
        "M09",
        "MA",
        "1-15",
        "PREDISSERTATION RSCH",
        "TBA",
        "-",
        "MANCR",
        "NCR",
        "Son Cao Tran (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "600",
        "M10",
        "MA",
        "1-15",
        "PREDISSERTATION RSCH",
        "TBA",
        "-",
        "MANCR",
        "NCR",
        "Tuan Le (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "600",
        "M11",
        "MA",
        "1-15",
        "PREDISSERTATION RSCH",
        "TBA",
        "-",
        "MANCR",
        "NCR",
        "Roopa Vishwanathan (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "600",
        "M12",
        "MA",
        "1-15",
        "PREDISSERTATION RSCH",
        "TBA",
        "-",
        "MANCR",
        "NCR",
        "Zachary Oliver Toups (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "700",
        "M01",
        "MA",
        "1-15",
        "DOCTORAL DISSERTATION",
        "TBA",
        "-",
        "MANCR",
        "NCR",
        "Huiping Cao (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "700",
        "M02",
        "MA",
        "1-15",
        "DOCTORAL DISSERTATION",
        "TBA",
        "-",
        "MANCR",
        "NCR",
        "Jonathan E. Cook (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "700",
        "M03",
        "MA",
        "1-15",
        "DOCTORAL DISSERTATION",
        "TBA",
        "-",
        "MANCR",
        "NCR",
        "William A Hamilton (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "700",
        "M05",
        "MA",
        "1-15",
        "DOCTORAL DISSERTATION",
        "TBA",
        "-",
        "MANCR",
        "NCR",
        "Satyajayant Misra (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "700",
        "M06",
        "MA",
        "1-15",
        "DOCTORAL DISSERTATION",
        "TBA",
        "-",
        "MANCR",
        "NCR",
        "Inna V. Pivkina (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "700",
        "M07",
        "MA",
        "1-15",
        "DOCTORAL DISSERTATION",
        "TBA",
        "-",
        "MANCR",
        "NCR",
        "Enrico Pontelli (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "700",
        "M08",
        "MA",
        "1-15",
        "DOCTORAL DISSERTATION",
        "TBA",
        "-",
        "MANCR",
        "NCR",
        "Mingzhou Song (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "700",
        "M09",
        "MA",
        "1-15",
        "DOCTORAL DISSERTATION",
        "TBA",
        "-",
        "MANCR",
        "NCR",
        "Son Cao Tran (P)",
        "01/22-05/15",
    ),
    (
        "C S",
        "700",
        "M12",
        "MA",
        "1-15",
        "DOCTORAL DISSERTATION",
        "TBA",
        "-",
        "MANCR",
        "NCR",
        "Zachary Oliver Toups (P)",
        "01/22-05/15",
    ),
]
